### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gearsdigital** [hypermodules/gh-release#69]
I've installed `gh-release` globally but after running `gh-release` from my project root I get the following error.

```js
/usr/local/lib/node_modules/gh-release/node_modules/changelog-parser/index.js:119
  delete data.current._private
              ^

TypeError: Cannot convert undefined or null to object
    at pushCurrent (/usr/local/lib/node_modules/gh-release/node_modules/changelog-parser/index.js:119:15)
    at /usr/local/lib/node_modules/gh-release/node_modules/changelog-parser/index.js:35:7
    at finish (/usr/local/lib/node_modules/gh-release/node_modules/line-reader/lib/line_reader.js:123:9)
    at newRead (/usr/local/lib/node_modules/gh-release/node_modules/line-reader/lib/line_reader.js:132:11)
    at /usr/local/lib/node_modules/gh-release/node_modules/line-reader/lib/line_reader.js:153:15
    at getLine (/usr/local/lib/node_modules/gh-release/node_modules/line-reader/lib/line_reader.js:74:9)
    at LineReader.nextLine (/usr/local/lib/node_modules/gh-release/node_modules/line-reader/lib/line_reader.js:93:9)
    at Immediate.readNext [as _onImmediate] (/usr/local/lib/node_modules/gh-release/node_modules/line-reader/lib/line_reader.js:146:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
```

This is my current environment:

```bash
npm -v && node -v
5.6.0
v8.9.1
```

**Comment by gearsdigital** [comment]
A Little hint would ne nice 😜 You could ask to create one for the user. That would be very convienient :)

**Comment by jgravois** [comment]
> A little hint would be nice 😜

@gearsdigital you want to take a stab at a patch? #61 is a decent reference point.

**Comment by gearsdigital** [comment]
Yeah, I'll take look.

**Comment by eamodio** [comment]
@ungoldman @jgravois I'm seeing this issue on both of my Windows machines and it doesn't have anything to do with an empty changelog. I think it *might* have something to do with line-endings, but not sure. Things used to work up until a month or so ago.

**Comment by eamodio** [comment]
Anyone have any ideas on the above?

**Comment by ungoldman** [comment]
I think the main problem described in this issue is resolved by the latest release (#81).

@eamodio if your problem (which sounds different from the above problem) persists can you please create a new issue reporting what happens and any environment/OS info you can share? Thank you! 🙏
