### ISSUE TITLE
Issue with autochangelog

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/gh-release#84]
When publishing with an [autochangelog](https://github.com/CookPete/auto-changelog) log, this crashes.  Maybe it's not spec compliant. 

```console
bret-netlify:netlify-identity-widget bret$ ./node_modules/.bin/gh-release 
/Users/bret/netlify/netlify-identity-widget/node_modules/changelog-parser/index.js:119
  delete data.current._private
              ^

TypeError: Cannot convert undefined or null to object
    at pushCurrent (/Users/bret/netlify/netlify-identity-widget/node_modules/changelog-parser/index.js:119:15)
    at /Users/bret/netlify/netlify-identity-widget/node_modules/changelog-parser/index.js:35:7
    at finish (/Users/bret/netlify/netlify-identity-widget/node_modules/line-reader/lib/line_reader.js:123:9)
    at newRead (/Users/bret/netlify/netlify-identity-widget/node_modules/line-reader/lib/line_reader.js:132:11)
    at /Users/bret/netlify/netlify-identity-widget/node_modules/line-reader/lib/line_reader.js:153:15
    at getLine (/Users/bret/netlify/netlify-identity-widget/node_modules/line-reader/lib/line_reader.js:74:9)
    at /Users/bret/netlify/netlify-identity-widget/node_modules/line-reader/lib/line_reader.js:56:13
    at FSReqCallback.wrapper [as oncomplete] (fs.js:481:5)
```

**Comment by bcomnes** [comment]
Oh nevermind, wrong format.  Maybe we should handle the error better though.

**Comment by bcomnes** [comment]
Closing in favor of 107
